name: run_with_print
description: Helper for getting the print output in tests.
version: 0.0.2
homepage: https://github.com/dev-yakuza/bull
repository: https://github.com/dev-yakuza/bull

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:

dev_dependencies:
  bull: ^0.0.5
  lints: ">=2.1.1 <4.0.0"
  test: ^1.24.6
